main: andreiwasfound.nightvisioncommand.Main
name: NightVisionCommand
author: AndreiWasFound
version: 1.1

commands:
  nv:
    permission: nightvisioncommand.use
    description: Give yourself night vision
    aliases:
      - nightvision